/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as announcements_index from "../announcements/index.js";
import type * as announcements_mutations_createAnnouncement from "../announcements/mutations/createAnnouncement.js";
import type * as announcements_mutations_deleteAnnouncement from "../announcements/mutations/deleteAnnouncement.js";
import type * as announcements_mutations_index from "../announcements/mutations/index.js";
import type * as announcements_mutations_manageAcknowledgment from "../announcements/mutations/manageAcknowledgment.js";
import type * as announcements_mutations_restoreAnnouncement from "../announcements/mutations/restoreAnnouncement.js";
import type * as announcements_mutations_updateAnnouncement from "../announcements/mutations/updateAnnouncement.js";
import type * as announcements_mutations_updateAnnouncementStats from "../announcements/mutations/updateAnnouncementStats.js";
import type * as announcements_queries_getAnnouncementAnalytics from "../announcements/queries/getAnnouncementAnalytics.js";
import type * as announcements_queries_getAnnouncementById from "../announcements/queries/getAnnouncementById.js";
import type * as announcements_queries_getAnnouncements from "../announcements/queries/getAnnouncements.js";
import type * as announcements_queries_getPinnedAnnouncements from "../announcements/queries/getPinnedAnnouncements.js";
import type * as announcements_queries_index from "../announcements/queries/index.js";
import type * as announcements_queries_searchAnnouncements from "../announcements/queries/searchAnnouncements.js";
import type * as carts_mutations_addGuestItems from "../carts/mutations/addGuestItems.js";
import type * as carts_mutations_addItem from "../carts/mutations/addItem.js";
import type * as carts_mutations_clearCart from "../carts/mutations/clearCart.js";
import type * as carts_mutations_createOrGetCart from "../carts/mutations/createOrGetCart.js";
import type * as carts_mutations_index from "../carts/mutations/index.js";
import type * as carts_mutations_markAbandoned from "../carts/mutations/markAbandoned.js";
import type * as carts_mutations_mergeCarts from "../carts/mutations/mergeCarts.js";
import type * as carts_mutations_removeItem from "../carts/mutations/removeItem.js";
import type * as carts_mutations_removeMultipleItems from "../carts/mutations/removeMultipleItems.js";
import type * as carts_mutations_setItemNote from "../carts/mutations/setItemNote.js";
import type * as carts_mutations_setItemSelected from "../carts/mutations/setItemSelected.js";
import type * as carts_mutations_updateCartStats from "../carts/mutations/updateCartStats.js";
import type * as carts_mutations_updateItemQuantity from "../carts/mutations/updateItemQuantity.js";
import type * as carts_mutations_updateItemVariant from "../carts/mutations/updateItemVariant.js";
import type * as carts_queries_getAbandonedCarts from "../carts/queries/getAbandonedCarts.js";
import type * as carts_queries_getCartById from "../carts/queries/getCartById.js";
import type * as carts_queries_getCartByUser from "../carts/queries/getCartByUser.js";
import type * as carts_queries_getCartSummary from "../carts/queries/getCartSummary.js";
import type * as carts_queries_index from "../carts/queries/index.js";
import type * as categories_mutations_createCategory from "../categories/mutations/createCategory.js";
import type * as categories_mutations_deleteCategory from "../categories/mutations/deleteCategory.js";
import type * as categories_mutations_index from "../categories/mutations/index.js";
import type * as categories_mutations_restoreCategory from "../categories/mutations/restoreCategory.js";
import type * as categories_mutations_updateCategory from "../categories/mutations/updateCategory.js";
import type * as categories_mutations_updateCategoryStats from "../categories/mutations/updateCategoryStats.js";
import type * as categories_queries_getCategories from "../categories/queries/getCategories.js";
import type * as categories_queries_getCategoryAnalytics from "../categories/queries/getCategoryAnalytics.js";
import type * as categories_queries_getCategoryById from "../categories/queries/getCategoryById.js";
import type * as categories_queries_getCategoryBySlug from "../categories/queries/getCategoryBySlug.js";
import type * as categories_queries_getCategoryHierarchy from "../categories/queries/getCategoryHierarchy.js";
import type * as categories_queries_getPopularCategories from "../categories/queries/getPopularCategories.js";
import type * as categories_queries_index from "../categories/queries/index.js";
import type * as categories_queries_searchCategories from "../categories/queries/searchCategories.js";
import type * as chats_index from "../chats/index.js";
import type * as chats_mutations_createChatRoom from "../chats/mutations/createChatRoom.js";
import type * as chats_mutations_index from "../chats/mutations/index.js";
import type * as chats_mutations_manageMessage from "../chats/mutations/manageMessage.js";
import type * as chats_mutations_manageParticipants from "../chats/mutations/manageParticipants.js";
import type * as chats_mutations_sendMessage from "../chats/mutations/sendMessage.js";
import type * as chats_mutations_updateRoom from "../chats/mutations/updateRoom.js";
import type * as chats_mutations_updateTyping from "../chats/mutations/updateTyping.js";
import type * as chats_queries_getChatRoomById from "../chats/queries/getChatRoomById.js";
import type * as chats_queries_getChatRooms from "../chats/queries/getChatRooms.js";
import type * as chats_queries_getChatRoomsPage from "../chats/queries/getChatRoomsPage.js";
import type * as chats_queries_getMessages from "../chats/queries/getMessages.js";
import type * as chats_queries_getTypingUsers from "../chats/queries/getTypingUsers.js";
import type * as chats_queries_getUnreadCount from "../chats/queries/getUnreadCount.js";
import type * as chats_queries_getUnreadCounts from "../chats/queries/getUnreadCounts.js";
import type * as chats_queries_index from "../chats/queries/index.js";
import type * as chats_queries_searchChats from "../chats/queries/searchChats.js";
import type * as chatwoot_actions_agentBot from "../chatwoot/actions/agentBot.js";
import type * as chatwoot_actions_processWebhook from "../chatwoot/actions/processWebhook.js";
import type * as chatwoot_fonts from "../chatwoot/fonts.js";
import type * as chatwoot_index from "../chatwoot/index.js";
import type * as chatwoot_keywordConfig from "../chatwoot/keywordConfig.js";
import type * as chatwoot_orderFlow_completeOrder from "../chatwoot/orderFlow/completeOrder.js";
import type * as chatwoot_orderFlow_createMessengerOrder from "../chatwoot/orderFlow/createMessengerOrder.js";
import type * as chatwoot_orderFlow_emailHandlers from "../chatwoot/orderFlow/emailHandlers.js";
import type * as chatwoot_orderFlow_emailVerification from "../chatwoot/orderFlow/emailVerification.js";
import type * as chatwoot_orderFlow_index from "../chatwoot/orderFlow/index.js";
import type * as chatwoot_orderFlow_messageBuilder from "../chatwoot/orderFlow/messageBuilder.js";
import type * as chatwoot_orderFlow_orderStepHandlers from "../chatwoot/orderFlow/orderStepHandlers.js";
import type * as chatwoot_orderFlow_sendOTPEmail from "../chatwoot/orderFlow/sendOTPEmail.js";
import type * as chatwoot_orderFlow_sendPaymentConfirmation from "../chatwoot/orderFlow/sendPaymentConfirmation.js";
import type * as chatwoot_orderFlow_sessionManager from "../chatwoot/orderFlow/sessionManager.js";
import type * as chatwoot_orderFlow_startOrderFlow from "../chatwoot/orderFlow/startOrderFlow.js";
import type * as chatwoot_orderFlow_types from "../chatwoot/orderFlow/types.js";
import type * as chatwoot_types from "../chatwoot/types.js";
import type * as checkoutSessions_index from "../checkoutSessions/index.js";
import type * as checkoutSessions_mutations_createCheckoutSession from "../checkoutSessions/mutations/createCheckoutSession.js";
import type * as checkoutSessions_mutations_index from "../checkoutSessions/mutations/index.js";
import type * as checkoutSessions_mutations_markInvoiceCreated from "../checkoutSessions/mutations/markInvoiceCreated.js";
import type * as checkoutSessions_mutations_updateCheckoutSessionInvoice from "../checkoutSessions/mutations/updateCheckoutSessionInvoice.js";
import type * as checkoutSessions_mutations_updateCheckoutSessionPaymongoCheckout from "../checkoutSessions/mutations/updateCheckoutSessionPaymongoCheckout.js";
import type * as checkoutSessions_queries_getCheckoutSessionById from "../checkoutSessions/queries/getCheckoutSessionById.js";
import type * as checkoutSessions_queries_index from "../checkoutSessions/queries/index.js";
import type * as crons from "../crons.js";
import type * as files_actions from "../files/actions.js";
import type * as files_index from "../files/index.js";
import type * as files_mutations_deleteFile from "../files/mutations/deleteFile.js";
import type * as files_mutations_index from "../files/mutations/index.js";
import type * as files_queries_getFileById from "../files/queries/getFileById.js";
import type * as files_queries_getFilesByEntity from "../files/queries/getFilesByEntity.js";
import type * as files_queries_getFilesByUser from "../files/queries/getFilesByUser.js";
import type * as files_queries_getPublicUrl from "../files/queries/getPublicUrl.js";
import type * as files_queries_index from "../files/queries/index.js";
import type * as files_r2 from "../files/r2.js";
import type * as guestCheckout_index from "../guestCheckout/index.js";
import type * as guestCheckout_mutations_createGuestOrder from "../guestCheckout/mutations/createGuestOrder.js";
import type * as guestCheckout_mutations_sendOTP from "../guestCheckout/mutations/sendOTP.js";
import type * as guestCheckout_mutations_verifyOTP from "../guestCheckout/mutations/verifyOTP.js";
import type * as helpers_auth from "../helpers/auth.js";
import type * as helpers_emailTemplates_builders from "../helpers/emailTemplates/builders.js";
import type * as helpers_emailTemplates_constants from "../helpers/emailTemplates/constants.js";
import type * as helpers_emailTemplates_index from "../helpers/emailTemplates/index.js";
import type * as helpers_emailTemplates_mailgunClient from "../helpers/emailTemplates/mailgunClient.js";
import type * as helpers_emailTemplates_orderConfirmation from "../helpers/emailTemplates/orderConfirmation.js";
import type * as helpers_emailTemplates_paymentConfirmation from "../helpers/emailTemplates/paymentConfirmation.js";
import type * as helpers_emailTemplates_paymentReceived from "../helpers/emailTemplates/paymentReceived.js";
import type * as helpers_emailTemplates_payoutInvoiceReady from "../helpers/emailTemplates/payoutInvoiceReady.js";
import type * as helpers_emailTemplates_preview from "../helpers/emailTemplates/preview.js";
import type * as helpers_emailTemplates_refundApproved from "../helpers/emailTemplates/refundApproved.js";
import type * as helpers_emailTemplates_refundRejected from "../helpers/emailTemplates/refundRejected.js";
import type * as helpers_emailTemplates_refundRequestReceived from "../helpers/emailTemplates/refundRequestReceived.js";
import type * as helpers_emailTemplates_shippingUpdate from "../helpers/emailTemplates/shippingUpdate.js";
import type * as helpers_emailTemplates_welcomeEmail from "../helpers/emailTemplates/welcomeEmail.js";
import type * as helpers_index from "../helpers/index.js";
import type * as helpers_organizations from "../helpers/organizations.js";
import type * as helpers_permissions from "../helpers/permissions.js";
import type * as helpers_utils from "../helpers/utils.js";
import type * as helpers_validation from "../helpers/validation.js";
import type * as http from "../http.js";
import type * as httpActions_chatwootWebhook from "../httpActions/chatwootWebhook.js";
import type * as httpActions_clerkWebhook from "../httpActions/clerkWebhook.js";
import type * as httpActions_index from "../httpActions/index.js";
import type * as httpActions_paymongoWebhook from "../httpActions/paymongoWebhook.js";
import type * as httpActions_productsFeed from "../httpActions/productsFeed.js";
import type * as httpActions_resolveOrg from "../httpActions/resolveOrg.js";
import type * as httpActions_xenditWebhook from "../httpActions/xenditWebhook.js";
import type * as logs_index from "../logs/index.js";
import type * as logs_mutations_index from "../logs/mutations/index.js";
import type * as logs_mutations_logArchive from "../logs/mutations/logArchive.js";
import type * as logs_mutations_logCreate from "../logs/mutations/logCreate.js";
import type * as logs_mutations_logCreateInternal from "../logs/mutations/logCreateInternal.js";
import type * as logs_mutations_logDelete from "../logs/mutations/logDelete.js";
import type * as logs_mutations_logRestore from "../logs/mutations/logRestore.js";
import type * as logs_queries_index from "../logs/queries/index.js";
import type * as logs_queries_logById from "../logs/queries/logById.js";
import type * as logs_queries_logsAnalytics from "../logs/queries/logsAnalytics.js";
import type * as logs_queries_logsList from "../logs/queries/logsList.js";
import type * as logs_queries_logsSearch from "../logs/queries/logsSearch.js";
import type * as messages_mutations_createMessage from "../messages/mutations/createMessage.js";
import type * as messages_mutations_deleteMessage from "../messages/mutations/deleteMessage.js";
import type * as messages_mutations_index from "../messages/mutations/index.js";
import type * as messages_mutations_replyToMessage from "../messages/mutations/replyToMessage.js";
import type * as messages_mutations_restoreMessage from "../messages/mutations/restoreMessage.js";
import type * as messages_mutations_updateMessage from "../messages/mutations/updateMessage.js";
import type * as messages_mutations_updateMessageStats from "../messages/mutations/updateMessageStats.js";
import type * as messages_queries_getConversation from "../messages/queries/getConversation.js";
import type * as messages_queries_getMessageAnalytics from "../messages/queries/getMessageAnalytics.js";
import type * as messages_queries_getMessageById from "../messages/queries/getMessageById.js";
import type * as messages_queries_getMessages from "../messages/queries/getMessages.js";
import type * as messages_queries_getMessagesByEmail from "../messages/queries/getMessagesByEmail.js";
import type * as messages_queries_index from "../messages/queries/index.js";
import type * as messages_queries_searchMessages from "../messages/queries/searchMessages.js";
import type * as migrations_backfillCheckoutSessionExpiresAt from "../migrations/backfillCheckoutSessionExpiresAt.js";
import type * as migrations_backfillImageUrls from "../migrations/backfillImageUrls.js";
import type * as migrations_backfillOrderLogs from "../migrations/backfillOrderLogs.js";
import type * as migrations_backfillPaidAt from "../migrations/backfillPaidAt.js";
import type * as migrations_migrateVoucherSchema from "../migrations/migrateVoucherSchema.js";
import type * as models_announcements from "../models/announcements.js";
import type * as models_carts from "../models/carts.js";
import type * as models_categories from "../models/categories.js";
import type * as models_chats from "../models/chats.js";
import type * as models_chatwoot from "../models/chatwoot.js";
import type * as models_checkoutSessions from "../models/checkoutSessions.js";
import type * as models_files from "../models/files.js";
import type * as models_logs from "../models/logs.js";
import type * as models_messages from "../models/messages.js";
import type * as models_messengerOrders from "../models/messengerOrders.js";
import type * as models_orderBatches from "../models/orderBatches.js";
import type * as models_orders from "../models/orders.js";
import type * as models_organizations from "../models/organizations.js";
import type * as models_payments from "../models/payments.js";
import type * as models_payoutAdjustments from "../models/payoutAdjustments.js";
import type * as models_payouts from "../models/payouts.js";
import type * as models_permissions from "../models/permissions.js";
import type * as models_products from "../models/products.js";
import type * as models_refundRequests from "../models/refundRequests.js";
import type * as models_storefrontApplications from "../models/storefrontApplications.js";
import type * as models_surveys from "../models/surveys.js";
import type * as models_tickets from "../models/tickets.js";
import type * as models_users from "../models/users.js";
import type * as models_voucherRedemptionCosts from "../models/voucherRedemptionCosts.js";
import type * as models_voucherRefundRequests from "../models/voucherRefundRequests.js";
import type * as models_vouchers from "../models/vouchers.js";
import type * as orderBatches_index from "../orderBatches/index.js";
import type * as orderBatches_mutations_assignOrdersToBatch from "../orderBatches/mutations/assignOrdersToBatch.js";
import type * as orderBatches_mutations_bulkUpdateBatchOrders from "../orderBatches/mutations/bulkUpdateBatchOrders.js";
import type * as orderBatches_mutations_createBatch from "../orderBatches/mutations/createBatch.js";
import type * as orderBatches_mutations_deleteBatch from "../orderBatches/mutations/deleteBatch.js";
import type * as orderBatches_mutations_index from "../orderBatches/mutations/index.js";
import type * as orderBatches_mutations_removeOrdersFromBatch from "../orderBatches/mutations/removeOrdersFromBatch.js";
import type * as orderBatches_mutations_updateBatch from "../orderBatches/mutations/updateBatch.js";
import type * as orderBatches_queries_getBatchById from "../orderBatches/queries/getBatchById.js";
import type * as orderBatches_queries_getBatchOrders from "../orderBatches/queries/getBatchOrders.js";
import type * as orderBatches_queries_getBatches from "../orderBatches/queries/getBatches.js";
import type * as orderBatches_queries_index from "../orderBatches/queries/index.js";
import type * as orders_actions_sendOrderConfirmationEmail from "../orders/actions/sendOrderConfirmationEmail.js";
import type * as orders_actions_sendOrderStatusEmail from "../orders/actions/sendOrderStatusEmail.js";
import type * as orders_mutations_cancelOrder from "../orders/mutations/cancelOrder.js";
import type * as orders_mutations_confirmOrderReceived from "../orders/mutations/confirmOrderReceived.js";
import type * as orders_mutations_createOrder from "../orders/mutations/createOrder.js";
import type * as orders_mutations_createOrderLog from "../orders/mutations/createOrderLog.js";
import type * as orders_mutations_createPaymongoCheckoutForOrder from "../orders/mutations/createPaymongoCheckoutForOrder.js";
import type * as orders_mutations_createXenditInvoiceForOrder from "../orders/mutations/createXenditInvoiceForOrder.js";
import type * as orders_mutations_deleteOrder from "../orders/mutations/deleteOrder.js";
import type * as orders_mutations_index from "../orders/mutations/index.js";
import type * as orders_mutations_processCreateOrder from "../orders/mutations/processCreateOrder.js";
import type * as orders_mutations_refreshPaymongoCheckout from "../orders/mutations/refreshPaymongoCheckout.js";
import type * as orders_mutations_refreshXenditInvoice from "../orders/mutations/refreshXenditInvoice.js";
import type * as orders_mutations_restoreOrder from "../orders/mutations/restoreOrder.js";
import type * as orders_mutations_updateOrder from "../orders/mutations/updateOrder.js";
import type * as orders_mutations_updateOrderPaymongoCheckout from "../orders/mutations/updateOrderPaymongoCheckout.js";
import type * as orders_mutations_updateOrderStats from "../orders/mutations/updateOrderStats.js";
import type * as orders_mutations_updateOrderWithNote from "../orders/mutations/updateOrderWithNote.js";
import type * as orders_mutations_updateOrderXenditInvoice from "../orders/mutations/updateOrderXenditInvoice.js";
import type * as orders_mutations_updateOrdersInvoiceForSession from "../orders/mutations/updateOrdersInvoiceForSession.js";
import type * as orders_queries_getDashboardAnalytics from "../orders/queries/getDashboardAnalytics.js";
import type * as orders_queries_getOrderAnalytics from "../orders/queries/getOrderAnalytics.js";
import type * as orders_queries_getOrderById from "../orders/queries/getOrderById.js";
import type * as orders_queries_getOrderLogs from "../orders/queries/getOrderLogs.js";
import type * as orders_queries_getOrders from "../orders/queries/getOrders.js";
import type * as orders_queries_getOrdersByCheckoutSession from "../orders/queries/getOrdersByCheckoutSession.js";
import type * as orders_queries_getOrdersPage from "../orders/queries/getOrdersPage.js";
import type * as orders_queries_index from "../orders/queries/index.js";
import type * as orders_queries_searchOrders from "../orders/queries/searchOrders.js";
import type * as organizations_mutations_addMember from "../organizations/mutations/addMember.js";
import type * as organizations_mutations_createInviteLink from "../organizations/mutations/createInviteLink.js";
import type * as organizations_mutations_createOrganization from "../organizations/mutations/createOrganization.js";
import type * as organizations_mutations_deactivateInviteLink from "../organizations/mutations/deactivateInviteLink.js";
import type * as organizations_mutations_deleteOrganization from "../organizations/mutations/deleteOrganization.js";
import type * as organizations_mutations_index from "../organizations/mutations/index.js";
import type * as organizations_mutations_joinOrganization from "../organizations/mutations/joinOrganization.js";
import type * as organizations_mutations_joinPublicOrganization from "../organizations/mutations/joinPublicOrganization.js";
import type * as organizations_mutations_removeMember from "../organizations/mutations/removeMember.js";
import type * as organizations_mutations_requestToJoinOrganization from "../organizations/mutations/requestToJoinOrganization.js";
import type * as organizations_mutations_reviewJoinRequest from "../organizations/mutations/reviewJoinRequest.js";
import type * as organizations_mutations_updateChatwootConfig from "../organizations/mutations/updateChatwootConfig.js";
import type * as organizations_mutations_updateMemberActivity from "../organizations/mutations/updateMemberActivity.js";
import type * as organizations_mutations_updateMemberRole from "../organizations/mutations/updateMemberRole.js";
import type * as organizations_mutations_updateOrganization from "../organizations/mutations/updateOrganization.js";
import type * as organizations_mutations_updateOrganizationStats from "../organizations/mutations/updateOrganizationStats.js";
import type * as organizations_queries_checkOrganizationPermission from "../organizations/queries/checkOrganizationPermission.js";
import type * as organizations_queries_getChatwootConfig from "../organizations/queries/getChatwootConfig.js";
import type * as organizations_queries_getInviteLinkByCode from "../organizations/queries/getInviteLinkByCode.js";
import type * as organizations_queries_getMyJoinRequestStatus from "../organizations/queries/getMyJoinRequestStatus.js";
import type * as organizations_queries_getOrganizationAnalytics from "../organizations/queries/getOrganizationAnalytics.js";
import type * as organizations_queries_getOrganizationById from "../organizations/queries/getOrganizationById.js";
import type * as organizations_queries_getOrganizationByName from "../organizations/queries/getOrganizationByName.js";
import type * as organizations_queries_getOrganizationBySlug from "../organizations/queries/getOrganizationBySlug.js";
import type * as organizations_queries_getOrganizationInviteLinks from "../organizations/queries/getOrganizationInviteLinks.js";
import type * as organizations_queries_getOrganizationMembers from "../organizations/queries/getOrganizationMembers.js";
import type * as organizations_queries_getOrganizations from "../organizations/queries/getOrganizations.js";
import type * as organizations_queries_getOrganizationsByUser from "../organizations/queries/getOrganizationsByUser.js";
import type * as organizations_queries_getPopularOrganizations from "../organizations/queries/getPopularOrganizations.js";
import type * as organizations_queries_index from "../organizations/queries/index.js";
import type * as organizations_queries_listJoinRequests from "../organizations/queries/listJoinRequests.js";
import type * as organizations_queries_searchOrganizations from "../organizations/queries/searchOrganizations.js";
import type * as payments_actions_createGroupedPaymongoCheckout from "../payments/actions/createGroupedPaymongoCheckout.js";
import type * as payments_actions_createGroupedXenditInvoice from "../payments/actions/createGroupedXenditInvoice.js";
import type * as payments_actions_createXenditInvoice from "../payments/actions/createXenditInvoice.js";
import type * as payments_actions_index from "../payments/actions/index.js";
import type * as payments_actions_paymongoService from "../payments/actions/paymongoService.js";
import type * as payments_actions_sendPaymentConfirmationEmail from "../payments/actions/sendPaymentConfirmationEmail.js";
import type * as payments_actions_xenditService from "../payments/actions/xenditService.js";
import type * as payments_index from "../payments/index.js";
import type * as payments_mutations_createPayment from "../payments/mutations/createPayment.js";
import type * as payments_mutations_deletePayment from "../payments/mutations/deletePayment.js";
import type * as payments_mutations_handleCheckoutSessionExpiry from "../payments/mutations/handleCheckoutSessionExpiry.js";
import type * as payments_mutations_handlePaymongoWebhook from "../payments/mutations/handlePaymongoWebhook.js";
import type * as payments_mutations_handleXenditWebhook from "../payments/mutations/handleXenditWebhook.js";
import type * as payments_mutations_index from "../payments/mutations/index.js";
import type * as payments_mutations_refundPayment from "../payments/mutations/refundPayment.js";
import type * as payments_mutations_restorePayment from "../payments/mutations/restorePayment.js";
import type * as payments_mutations_updatePayment from "../payments/mutations/updatePayment.js";
import type * as payments_mutations_updatePaymentStats from "../payments/mutations/updatePaymentStats.js";
import type * as payments_queries_getPaymentAnalytics from "../payments/queries/getPaymentAnalytics.js";
import type * as payments_queries_getPaymentById from "../payments/queries/getPaymentById.js";
import type * as payments_queries_getPayments from "../payments/queries/getPayments.js";
import type * as payments_queries_index from "../payments/queries/index.js";
import type * as payments_queries_searchPayments from "../payments/queries/searchPayments.js";
import type * as payouts_actions_index from "../payouts/actions/index.js";
import type * as payouts_actions_nodeActions from "../payouts/actions/nodeActions.js";
import type * as payouts_actions_triggerActions from "../payouts/actions/triggerActions.js";
import type * as payouts_index from "../payouts/index.js";
import type * as payouts_mutations_generatePayoutInvoices from "../payouts/mutations/generatePayoutInvoices.js";
import type * as payouts_mutations_index from "../payouts/mutations/index.js";
import type * as payouts_mutations_markInvoicePaid from "../payouts/mutations/markInvoicePaid.js";
import type * as payouts_mutations_revertPayoutStatus from "../payouts/mutations/revertPayoutStatus.js";
import type * as payouts_mutations_updateInvoiceEmailSent from "../payouts/mutations/updateInvoiceEmailSent.js";
import type * as payouts_mutations_updateInvoicePdfUrl from "../payouts/mutations/updateInvoicePdfUrl.js";
import type * as payouts_mutations_updateOrgBankDetails from "../payouts/mutations/updateOrgBankDetails.js";
import type * as payouts_mutations_updateOrgPlatformFee from "../payouts/mutations/updateOrgPlatformFee.js";
import type * as payouts_mutations_updatePayoutSettings from "../payouts/mutations/updatePayoutSettings.js";
import type * as payouts_queries_getAuthorizedPayoutInvoice from "../payouts/queries/getAuthorizedPayoutInvoice.js";
import type * as payouts_queries_getPayoutAdjustments from "../payouts/queries/getPayoutAdjustments.js";
import type * as payouts_queries_getPayoutInvoiceById from "../payouts/queries/getPayoutInvoiceById.js";
import type * as payouts_queries_getPayoutInvoices from "../payouts/queries/getPayoutInvoices.js";
import type * as payouts_queries_getPayoutSettings from "../payouts/queries/getPayoutSettings.js";
import type * as payouts_queries_getPayoutSummary from "../payouts/queries/getPayoutSummary.js";
import type * as payouts_queries_getPendingCount from "../payouts/queries/getPendingCount.js";
import type * as payouts_queries_index from "../payouts/queries/index.js";
import type * as permissions_mutations_assignOrganizationPermission from "../permissions/mutations/assignOrganizationPermission.js";
import type * as permissions_mutations_assignUserPermission from "../permissions/mutations/assignUserPermission.js";
import type * as permissions_mutations_bulkAssignUserPermissions from "../permissions/mutations/bulkAssignUserPermissions.js";
import type * as permissions_mutations_createPermission from "../permissions/mutations/createPermission.js";
import type * as permissions_mutations_deletePermission from "../permissions/mutations/deletePermission.js";
import type * as permissions_mutations_index from "../permissions/mutations/index.js";
import type * as permissions_mutations_revokeOrganizationPermission from "../permissions/mutations/revokeOrganizationPermission.js";
import type * as permissions_mutations_revokeUserPermission from "../permissions/mutations/revokeUserPermission.js";
import type * as permissions_mutations_updatePermission from "../permissions/mutations/updatePermission.js";
import type * as permissions_queries_checkEntityPermission from "../permissions/queries/checkEntityPermission.js";
import type * as permissions_queries_getOrganizationMemberPermissions from "../permissions/queries/getOrganizationMemberPermissions.js";
import type * as permissions_queries_getPermissionAnalytics from "../permissions/queries/getPermissionAnalytics.js";
import type * as permissions_queries_getPermissionByCode from "../permissions/queries/getPermissionByCode.js";
import type * as permissions_queries_getPermissionById from "../permissions/queries/getPermissionById.js";
import type * as permissions_queries_getPermissionUsageSummary from "../permissions/queries/getPermissionUsageSummary.js";
import type * as permissions_queries_getPermissions from "../permissions/queries/getPermissions.js";
import type * as permissions_queries_getPermissionsByCategory from "../permissions/queries/getPermissionsByCategory.js";
import type * as permissions_queries_getUserPermissions from "../permissions/queries/getUserPermissions.js";
import type * as permissions_queries_index from "../permissions/queries/index.js";
import type * as permissions_queries_searchPermissions from "../permissions/queries/searchPermissions.js";
import type * as products_mutations_bulkOperations from "../products/mutations/bulkOperations.js";
import type * as products_mutations_createProduct from "../products/mutations/createProduct.js";
import type * as products_mutations_deleteProduct from "../products/mutations/deleteProduct.js";
import type * as products_mutations_index from "../products/mutations/index.js";
import type * as products_mutations_manageProductImages from "../products/mutations/manageProductImages.js";
import type * as products_mutations_manageVariants from "../products/mutations/manageVariants.js";
import type * as products_mutations_restoreProduct from "../products/mutations/restoreProduct.js";
import type * as products_mutations_updateProduct from "../products/mutations/updateProduct.js";
import type * as products_mutations_updateProductStats from "../products/mutations/updateProductStats.js";
import type * as products_queries_getAllActiveProducts from "../products/queries/getAllActiveProducts.js";
import type * as products_queries_getPopularProducts from "../products/queries/getPopularProducts.js";
import type * as products_queries_getProductAnalytics from "../products/queries/getProductAnalytics.js";
import type * as products_queries_getProductByCode from "../products/queries/getProductByCode.js";
import type * as products_queries_getProductById from "../products/queries/getProductById.js";
import type * as products_queries_getProductBySlug from "../products/queries/getProductBySlug.js";
import type * as products_queries_getProductRecommendations from "../products/queries/getProductRecommendations.js";
import type * as products_queries_getProducts from "../products/queries/getProducts.js";
import type * as products_queries_index from "../products/queries/index.js";
import type * as products_queries_searchProducts from "../products/queries/searchProducts.js";
import type * as refundRequests_actions_index from "../refundRequests/actions/index.js";
import type * as refundRequests_actions_sendRefundRequestEmail from "../refundRequests/actions/sendRefundRequestEmail.js";
import type * as refundRequests_index from "../refundRequests/index.js";
import type * as refundRequests_mutations_approveRefundRequest from "../refundRequests/mutations/approveRefundRequest.js";
import type * as refundRequests_mutations_createRefundNotification from "../refundRequests/mutations/createRefundNotification.js";
import type * as refundRequests_mutations_createRefundRequest from "../refundRequests/mutations/createRefundRequest.js";
import type * as refundRequests_mutations_createRefundVoucher from "../refundRequests/mutations/createRefundVoucher.js";
import type * as refundRequests_mutations_index from "../refundRequests/mutations/index.js";
import type * as refundRequests_mutations_rejectRefundRequest from "../refundRequests/mutations/rejectRefundRequest.js";
import type * as refundRequests_queries_getPendingCount from "../refundRequests/queries/getPendingCount.js";
import type * as refundRequests_queries_getRefundRequestById from "../refundRequests/queries/getRefundRequestById.js";
import type * as refundRequests_queries_getRefundRequestByOrder from "../refundRequests/queries/getRefundRequestByOrder.js";
import type * as refundRequests_queries_getRefundRequests from "../refundRequests/queries/getRefundRequests.js";
import type * as refundRequests_queries_getRefundRequestsByUser from "../refundRequests/queries/getRefundRequestsByUser.js";
import type * as refundRequests_queries_index from "../refundRequests/queries/index.js";
import type * as reviews_index from "../reviews/index.js";
import type * as reviews_mutations_createReview from "../reviews/mutations/createReview.js";
import type * as reviews_mutations_index from "../reviews/mutations/index.js";
import type * as reviews_mutations_updateReview from "../reviews/mutations/updateReview.js";
import type * as reviews_queries_getReviewsByProduct from "../reviews/queries/getReviewsByProduct.js";
import type * as reviews_queries_getUserReview from "../reviews/queries/getUserReview.js";
import type * as reviews_queries_index from "../reviews/queries/index.js";
import type * as seeds_index from "../seeds/index.js";
import type * as seeds_seedData from "../seeds/seedData.js";
import type * as seeds_seedPayoutAdjustments from "../seeds/seedPayoutAdjustments.js";
import type * as storefrontApplications_mutations_index from "../storefrontApplications/mutations/index.js";
import type * as storefrontApplications_mutations_submit from "../storefrontApplications/mutations/submit.js";
import type * as storefrontApplications_mutations_updateApplicationStatus from "../storefrontApplications/mutations/updateApplicationStatus.js";
import type * as storefrontApplications_mutations_updateStatus from "../storefrontApplications/mutations/updateStatus.js";
import type * as storefrontApplications_queries_index from "../storefrontApplications/queries/index.js";
import type * as storefrontApplications_queries_list from "../storefrontApplications/queries/list.js";
import type * as storefrontApplications_queries_listApplications from "../storefrontApplications/queries/listApplications.js";
import type * as surveys_index from "../surveys/index.js";
import type * as surveys_mutations_index from "../surveys/mutations/index.js";
import type * as surveys_mutations_manageSurveyCategory from "../surveys/mutations/manageSurveyCategory.js";
import type * as surveys_mutations_markSurveyResponseFollowUp from "../surveys/mutations/markSurveyResponseFollowUp.js";
import type * as surveys_mutations_submitSurveyResponse from "../surveys/mutations/submitSurveyResponse.js";
import type * as surveys_mutations_updateSurveyCategoryStats from "../surveys/mutations/updateSurveyCategoryStats.js";
import type * as surveys_queries_index from "../surveys/queries/index.js";
import type * as surveys_queries_surveyAnalytics from "../surveys/queries/surveyAnalytics.js";
import type * as surveys_queries_surveyCategories from "../surveys/queries/surveyCategories.js";
import type * as surveys_queries_surveyResponses from "../surveys/queries/surveyResponses.js";
import type * as testHelpers from "../testHelpers.js";
import type * as tickets_constants from "../tickets/constants.js";
import type * as tickets_index from "../tickets/index.js";
import type * as tickets_mutations_createTicket from "../tickets/mutations/createTicket.js";
import type * as tickets_mutations_deleteTicket from "../tickets/mutations/deleteTicket.js";
import type * as tickets_mutations_index from "../tickets/mutations/index.js";
import type * as tickets_mutations_manageAssignee from "../tickets/mutations/manageAssignee.js";
import type * as tickets_mutations_manageReads from "../tickets/mutations/manageReads.js";
import type * as tickets_mutations_manageTicketUpdates from "../tickets/mutations/manageTicketUpdates.js";
import type * as tickets_mutations_restoreTicket from "../tickets/mutations/restoreTicket.js";
import type * as tickets_mutations_updateTicket from "../tickets/mutations/updateTicket.js";
import type * as tickets_mutations_updateTicketStats from "../tickets/mutations/updateTicketStats.js";
import type * as tickets_queries_getOpenCount from "../tickets/queries/getOpenCount.js";
import type * as tickets_queries_getTicketAnalytics from "../tickets/queries/getTicketAnalytics.js";
import type * as tickets_queries_getTicketById from "../tickets/queries/getTicketById.js";
import type * as tickets_queries_getTicketUpdates from "../tickets/queries/getTicketUpdates.js";
import type * as tickets_queries_getTickets from "../tickets/queries/getTickets.js";
import type * as tickets_queries_getTicketsPage from "../tickets/queries/getTicketsPage.js";
import type * as tickets_queries_getUnreadCount from "../tickets/queries/getUnreadCount.js";
import type * as tickets_queries_index from "../tickets/queries/index.js";
import type * as tickets_queries_searchTickets from "../tickets/queries/searchTickets.js";
import type * as users_actions_generateChatwootHmac from "../users/actions/generateChatwootHmac.js";
import type * as users_actions_index from "../users/actions/index.js";
import type * as users_actions_sendWelcomeEmail from "../users/actions/sendWelcomeEmail.js";
import type * as users_mutations_addOrganizationMembership from "../users/mutations/addOrganizationMembership.js";
import type * as users_mutations_clerkWebhook from "../users/mutations/clerkWebhook.js";
import type * as users_mutations_completeOnboarding from "../users/mutations/completeOnboarding.js";
import type * as users_mutations_createChatwootHmacToken from "../users/mutations/createChatwootHmacToken.js";
import type * as users_mutations_deleteUser from "../users/mutations/deleteUser.js";
import type * as users_mutations_index from "../users/mutations/index.js";
import type * as users_mutations_removeOrganizationMembership from "../users/mutations/removeOrganizationMembership.js";
import type * as users_mutations_restoreUser from "../users/mutations/restoreUser.js";
import type * as users_mutations_updateAccountSettings from "../users/mutations/updateAccountSettings.js";
import type * as users_mutations_updateLastLogin from "../users/mutations/updateLastLogin.js";
import type * as users_mutations_updateOrderStats from "../users/mutations/updateOrderStats.js";
import type * as users_mutations_updatePreferences from "../users/mutations/updatePreferences.js";
import type * as users_mutations_updateProfile from "../users/mutations/updateProfile.js";
import type * as users_mutations_updateUserPermissions from "../users/mutations/updateUserPermissions.js";
import type * as users_mutations_updateUserRole from "../users/mutations/updateUserRole.js";
import type * as users_queries_checkUserPermission from "../users/queries/checkUserPermission.js";
import type * as users_queries_getAccountSettings from "../users/queries/getAccountSettings.js";
import type * as users_queries_getChatwootHmacToken from "../users/queries/getChatwootHmacToken.js";
import type * as users_queries_getCurrentUser from "../users/queries/getCurrentUser.js";
import type * as users_queries_getRecentlyActiveUsers from "../users/queries/getRecentlyActiveUsers.js";
import type * as users_queries_getUserAnalytics from "../users/queries/getUserAnalytics.js";
import type * as users_queries_getUserByEmail from "../users/queries/getUserByEmail.js";
import type * as users_queries_getUserById from "../users/queries/getUserById.js";
import type * as users_queries_getUsers from "../users/queries/getUsers.js";
import type * as users_queries_getUsersByManager from "../users/queries/getUsersByManager.js";
import type * as users_queries_getUsersByOrganization from "../users/queries/getUsersByOrganization.js";
import type * as users_queries_index from "../users/queries/index.js";
import type * as users_queries_searchUsers from "../users/queries/searchUsers.js";
import type * as voucherRefundRequests_index from "../voucherRefundRequests/index.js";
import type * as voucherRefundRequests_mutations_approveVoucherRefundRequest from "../voucherRefundRequests/mutations/approveVoucherRefundRequest.js";
import type * as voucherRefundRequests_mutations_createVoucherRefundRequest from "../voucherRefundRequests/mutations/createVoucherRefundRequest.js";
import type * as voucherRefundRequests_mutations_index from "../voucherRefundRequests/mutations/index.js";
import type * as voucherRefundRequests_mutations_rejectVoucherRefundRequest from "../voucherRefundRequests/mutations/rejectVoucherRefundRequest.js";
import type * as voucherRefundRequests_queries_getVoucherRefundRequestById from "../voucherRefundRequests/queries/getVoucherRefundRequestById.js";
import type * as voucherRefundRequests_queries_getVoucherRefundRequestCounts from "../voucherRefundRequests/queries/getVoucherRefundRequestCounts.js";
import type * as voucherRefundRequests_queries_getVoucherRefundRequests from "../voucherRefundRequests/queries/getVoucherRefundRequests.js";
import type * as voucherRefundRequests_queries_getVoucherRefundRequestsByUser from "../voucherRefundRequests/queries/getVoucherRefundRequestsByUser.js";
import type * as voucherRefundRequests_queries_getVoucherRefundRequestsByVoucher from "../voucherRefundRequests/queries/getVoucherRefundRequestsByVoucher.js";
import type * as voucherRefundRequests_queries_index from "../voucherRefundRequests/queries/index.js";
import type * as vouchers_index from "../vouchers/index.js";
import type * as vouchers_mutations_createVoucher from "../vouchers/mutations/createVoucher.js";
import type * as vouchers_mutations_deleteVoucher from "../vouchers/mutations/deleteVoucher.js";
import type * as vouchers_mutations_index from "../vouchers/mutations/index.js";
import type * as vouchers_mutations_toggleVoucherStatus from "../vouchers/mutations/toggleVoucherStatus.js";
import type * as vouchers_mutations_updateVoucher from "../vouchers/mutations/updateVoucher.js";
import type * as vouchers_queries_getVoucherByCode from "../vouchers/queries/getVoucherByCode.js";
import type * as vouchers_queries_getVoucherById from "../vouchers/queries/getVoucherById.js";
import type * as vouchers_queries_getVouchers from "../vouchers/queries/getVouchers.js";
import type * as vouchers_queries_getVouchersByUser from "../vouchers/queries/getVouchersByUser.js";
import type * as vouchers_queries_index from "../vouchers/queries/index.js";
import type * as vouchers_queries_validateVoucher from "../vouchers/queries/validateVoucher.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "announcements/index": typeof announcements_index;
  "announcements/mutations/createAnnouncement": typeof announcements_mutations_createAnnouncement;
  "announcements/mutations/deleteAnnouncement": typeof announcements_mutations_deleteAnnouncement;
  "announcements/mutations/index": typeof announcements_mutations_index;
  "announcements/mutations/manageAcknowledgment": typeof announcements_mutations_manageAcknowledgment;
  "announcements/mutations/restoreAnnouncement": typeof announcements_mutations_restoreAnnouncement;
  "announcements/mutations/updateAnnouncement": typeof announcements_mutations_updateAnnouncement;
  "announcements/mutations/updateAnnouncementStats": typeof announcements_mutations_updateAnnouncementStats;
  "announcements/queries/getAnnouncementAnalytics": typeof announcements_queries_getAnnouncementAnalytics;
  "announcements/queries/getAnnouncementById": typeof announcements_queries_getAnnouncementById;
  "announcements/queries/getAnnouncements": typeof announcements_queries_getAnnouncements;
  "announcements/queries/getPinnedAnnouncements": typeof announcements_queries_getPinnedAnnouncements;
  "announcements/queries/index": typeof announcements_queries_index;
  "announcements/queries/searchAnnouncements": typeof announcements_queries_searchAnnouncements;
  "carts/mutations/addGuestItems": typeof carts_mutations_addGuestItems;
  "carts/mutations/addItem": typeof carts_mutations_addItem;
  "carts/mutations/clearCart": typeof carts_mutations_clearCart;
  "carts/mutations/createOrGetCart": typeof carts_mutations_createOrGetCart;
  "carts/mutations/index": typeof carts_mutations_index;
  "carts/mutations/markAbandoned": typeof carts_mutations_markAbandoned;
  "carts/mutations/mergeCarts": typeof carts_mutations_mergeCarts;
  "carts/mutations/removeItem": typeof carts_mutations_removeItem;
  "carts/mutations/removeMultipleItems": typeof carts_mutations_removeMultipleItems;
  "carts/mutations/setItemNote": typeof carts_mutations_setItemNote;
  "carts/mutations/setItemSelected": typeof carts_mutations_setItemSelected;
  "carts/mutations/updateCartStats": typeof carts_mutations_updateCartStats;
  "carts/mutations/updateItemQuantity": typeof carts_mutations_updateItemQuantity;
  "carts/mutations/updateItemVariant": typeof carts_mutations_updateItemVariant;
  "carts/queries/getAbandonedCarts": typeof carts_queries_getAbandonedCarts;
  "carts/queries/getCartById": typeof carts_queries_getCartById;
  "carts/queries/getCartByUser": typeof carts_queries_getCartByUser;
  "carts/queries/getCartSummary": typeof carts_queries_getCartSummary;
  "carts/queries/index": typeof carts_queries_index;
  "categories/mutations/createCategory": typeof categories_mutations_createCategory;
  "categories/mutations/deleteCategory": typeof categories_mutations_deleteCategory;
  "categories/mutations/index": typeof categories_mutations_index;
  "categories/mutations/restoreCategory": typeof categories_mutations_restoreCategory;
  "categories/mutations/updateCategory": typeof categories_mutations_updateCategory;
  "categories/mutations/updateCategoryStats": typeof categories_mutations_updateCategoryStats;
  "categories/queries/getCategories": typeof categories_queries_getCategories;
  "categories/queries/getCategoryAnalytics": typeof categories_queries_getCategoryAnalytics;
  "categories/queries/getCategoryById": typeof categories_queries_getCategoryById;
  "categories/queries/getCategoryBySlug": typeof categories_queries_getCategoryBySlug;
  "categories/queries/getCategoryHierarchy": typeof categories_queries_getCategoryHierarchy;
  "categories/queries/getPopularCategories": typeof categories_queries_getPopularCategories;
  "categories/queries/index": typeof categories_queries_index;
  "categories/queries/searchCategories": typeof categories_queries_searchCategories;
  "chats/index": typeof chats_index;
  "chats/mutations/createChatRoom": typeof chats_mutations_createChatRoom;
  "chats/mutations/index": typeof chats_mutations_index;
  "chats/mutations/manageMessage": typeof chats_mutations_manageMessage;
  "chats/mutations/manageParticipants": typeof chats_mutations_manageParticipants;
  "chats/mutations/sendMessage": typeof chats_mutations_sendMessage;
  "chats/mutations/updateRoom": typeof chats_mutations_updateRoom;
  "chats/mutations/updateTyping": typeof chats_mutations_updateTyping;
  "chats/queries/getChatRoomById": typeof chats_queries_getChatRoomById;
  "chats/queries/getChatRooms": typeof chats_queries_getChatRooms;
  "chats/queries/getChatRoomsPage": typeof chats_queries_getChatRoomsPage;
  "chats/queries/getMessages": typeof chats_queries_getMessages;
  "chats/queries/getTypingUsers": typeof chats_queries_getTypingUsers;
  "chats/queries/getUnreadCount": typeof chats_queries_getUnreadCount;
  "chats/queries/getUnreadCounts": typeof chats_queries_getUnreadCounts;
  "chats/queries/index": typeof chats_queries_index;
  "chats/queries/searchChats": typeof chats_queries_searchChats;
  "chatwoot/actions/agentBot": typeof chatwoot_actions_agentBot;
  "chatwoot/actions/processWebhook": typeof chatwoot_actions_processWebhook;
  "chatwoot/fonts": typeof chatwoot_fonts;
  "chatwoot/index": typeof chatwoot_index;
  "chatwoot/keywordConfig": typeof chatwoot_keywordConfig;
  "chatwoot/orderFlow/completeOrder": typeof chatwoot_orderFlow_completeOrder;
  "chatwoot/orderFlow/createMessengerOrder": typeof chatwoot_orderFlow_createMessengerOrder;
  "chatwoot/orderFlow/emailHandlers": typeof chatwoot_orderFlow_emailHandlers;
  "chatwoot/orderFlow/emailVerification": typeof chatwoot_orderFlow_emailVerification;
  "chatwoot/orderFlow/index": typeof chatwoot_orderFlow_index;
  "chatwoot/orderFlow/messageBuilder": typeof chatwoot_orderFlow_messageBuilder;
  "chatwoot/orderFlow/orderStepHandlers": typeof chatwoot_orderFlow_orderStepHandlers;
  "chatwoot/orderFlow/sendOTPEmail": typeof chatwoot_orderFlow_sendOTPEmail;
  "chatwoot/orderFlow/sendPaymentConfirmation": typeof chatwoot_orderFlow_sendPaymentConfirmation;
  "chatwoot/orderFlow/sessionManager": typeof chatwoot_orderFlow_sessionManager;
  "chatwoot/orderFlow/startOrderFlow": typeof chatwoot_orderFlow_startOrderFlow;
  "chatwoot/orderFlow/types": typeof chatwoot_orderFlow_types;
  "chatwoot/types": typeof chatwoot_types;
  "checkoutSessions/index": typeof checkoutSessions_index;
  "checkoutSessions/mutations/createCheckoutSession": typeof checkoutSessions_mutations_createCheckoutSession;
  "checkoutSessions/mutations/index": typeof checkoutSessions_mutations_index;
  "checkoutSessions/mutations/markInvoiceCreated": typeof checkoutSessions_mutations_markInvoiceCreated;
  "checkoutSessions/mutations/updateCheckoutSessionInvoice": typeof checkoutSessions_mutations_updateCheckoutSessionInvoice;
  "checkoutSessions/mutations/updateCheckoutSessionPaymongoCheckout": typeof checkoutSessions_mutations_updateCheckoutSessionPaymongoCheckout;
  "checkoutSessions/queries/getCheckoutSessionById": typeof checkoutSessions_queries_getCheckoutSessionById;
  "checkoutSessions/queries/index": typeof checkoutSessions_queries_index;
  crons: typeof crons;
  "files/actions": typeof files_actions;
  "files/index": typeof files_index;
  "files/mutations/deleteFile": typeof files_mutations_deleteFile;
  "files/mutations/index": typeof files_mutations_index;
  "files/queries/getFileById": typeof files_queries_getFileById;
  "files/queries/getFilesByEntity": typeof files_queries_getFilesByEntity;
  "files/queries/getFilesByUser": typeof files_queries_getFilesByUser;
  "files/queries/getPublicUrl": typeof files_queries_getPublicUrl;
  "files/queries/index": typeof files_queries_index;
  "files/r2": typeof files_r2;
  "guestCheckout/index": typeof guestCheckout_index;
  "guestCheckout/mutations/createGuestOrder": typeof guestCheckout_mutations_createGuestOrder;
  "guestCheckout/mutations/sendOTP": typeof guestCheckout_mutations_sendOTP;
  "guestCheckout/mutations/verifyOTP": typeof guestCheckout_mutations_verifyOTP;
  "helpers/auth": typeof helpers_auth;
  "helpers/emailTemplates/builders": typeof helpers_emailTemplates_builders;
  "helpers/emailTemplates/constants": typeof helpers_emailTemplates_constants;
  "helpers/emailTemplates/index": typeof helpers_emailTemplates_index;
  "helpers/emailTemplates/mailgunClient": typeof helpers_emailTemplates_mailgunClient;
  "helpers/emailTemplates/orderConfirmation": typeof helpers_emailTemplates_orderConfirmation;
  "helpers/emailTemplates/paymentConfirmation": typeof helpers_emailTemplates_paymentConfirmation;
  "helpers/emailTemplates/paymentReceived": typeof helpers_emailTemplates_paymentReceived;
  "helpers/emailTemplates/payoutInvoiceReady": typeof helpers_emailTemplates_payoutInvoiceReady;
  "helpers/emailTemplates/preview": typeof helpers_emailTemplates_preview;
  "helpers/emailTemplates/refundApproved": typeof helpers_emailTemplates_refundApproved;
  "helpers/emailTemplates/refundRejected": typeof helpers_emailTemplates_refundRejected;
  "helpers/emailTemplates/refundRequestReceived": typeof helpers_emailTemplates_refundRequestReceived;
  "helpers/emailTemplates/shippingUpdate": typeof helpers_emailTemplates_shippingUpdate;
  "helpers/emailTemplates/welcomeEmail": typeof helpers_emailTemplates_welcomeEmail;
  "helpers/index": typeof helpers_index;
  "helpers/organizations": typeof helpers_organizations;
  "helpers/permissions": typeof helpers_permissions;
  "helpers/utils": typeof helpers_utils;
  "helpers/validation": typeof helpers_validation;
  http: typeof http;
  "httpActions/chatwootWebhook": typeof httpActions_chatwootWebhook;
  "httpActions/clerkWebhook": typeof httpActions_clerkWebhook;
  "httpActions/index": typeof httpActions_index;
  "httpActions/paymongoWebhook": typeof httpActions_paymongoWebhook;
  "httpActions/productsFeed": typeof httpActions_productsFeed;
  "httpActions/resolveOrg": typeof httpActions_resolveOrg;
  "httpActions/xenditWebhook": typeof httpActions_xenditWebhook;
  "logs/index": typeof logs_index;
  "logs/mutations/index": typeof logs_mutations_index;
  "logs/mutations/logArchive": typeof logs_mutations_logArchive;
  "logs/mutations/logCreate": typeof logs_mutations_logCreate;
  "logs/mutations/logCreateInternal": typeof logs_mutations_logCreateInternal;
  "logs/mutations/logDelete": typeof logs_mutations_logDelete;
  "logs/mutations/logRestore": typeof logs_mutations_logRestore;
  "logs/queries/index": typeof logs_queries_index;
  "logs/queries/logById": typeof logs_queries_logById;
  "logs/queries/logsAnalytics": typeof logs_queries_logsAnalytics;
  "logs/queries/logsList": typeof logs_queries_logsList;
  "logs/queries/logsSearch": typeof logs_queries_logsSearch;
  "messages/mutations/createMessage": typeof messages_mutations_createMessage;
  "messages/mutations/deleteMessage": typeof messages_mutations_deleteMessage;
  "messages/mutations/index": typeof messages_mutations_index;
  "messages/mutations/replyToMessage": typeof messages_mutations_replyToMessage;
  "messages/mutations/restoreMessage": typeof messages_mutations_restoreMessage;
  "messages/mutations/updateMessage": typeof messages_mutations_updateMessage;
  "messages/mutations/updateMessageStats": typeof messages_mutations_updateMessageStats;
  "messages/queries/getConversation": typeof messages_queries_getConversation;
  "messages/queries/getMessageAnalytics": typeof messages_queries_getMessageAnalytics;
  "messages/queries/getMessageById": typeof messages_queries_getMessageById;
  "messages/queries/getMessages": typeof messages_queries_getMessages;
  "messages/queries/getMessagesByEmail": typeof messages_queries_getMessagesByEmail;
  "messages/queries/index": typeof messages_queries_index;
  "messages/queries/searchMessages": typeof messages_queries_searchMessages;
  "migrations/backfillCheckoutSessionExpiresAt": typeof migrations_backfillCheckoutSessionExpiresAt;
  "migrations/backfillImageUrls": typeof migrations_backfillImageUrls;
  "migrations/backfillOrderLogs": typeof migrations_backfillOrderLogs;
  "migrations/backfillPaidAt": typeof migrations_backfillPaidAt;
  "migrations/migrateVoucherSchema": typeof migrations_migrateVoucherSchema;
  "models/announcements": typeof models_announcements;
  "models/carts": typeof models_carts;
  "models/categories": typeof models_categories;
  "models/chats": typeof models_chats;
  "models/chatwoot": typeof models_chatwoot;
  "models/checkoutSessions": typeof models_checkoutSessions;
  "models/files": typeof models_files;
  "models/logs": typeof models_logs;
  "models/messages": typeof models_messages;
  "models/messengerOrders": typeof models_messengerOrders;
  "models/orderBatches": typeof models_orderBatches;
  "models/orders": typeof models_orders;
  "models/organizations": typeof models_organizations;
  "models/payments": typeof models_payments;
  "models/payoutAdjustments": typeof models_payoutAdjustments;
  "models/payouts": typeof models_payouts;
  "models/permissions": typeof models_permissions;
  "models/products": typeof models_products;
  "models/refundRequests": typeof models_refundRequests;
  "models/storefrontApplications": typeof models_storefrontApplications;
  "models/surveys": typeof models_surveys;
  "models/tickets": typeof models_tickets;
  "models/users": typeof models_users;
  "models/voucherRedemptionCosts": typeof models_voucherRedemptionCosts;
  "models/voucherRefundRequests": typeof models_voucherRefundRequests;
  "models/vouchers": typeof models_vouchers;
  "orderBatches/index": typeof orderBatches_index;
  "orderBatches/mutations/assignOrdersToBatch": typeof orderBatches_mutations_assignOrdersToBatch;
  "orderBatches/mutations/bulkUpdateBatchOrders": typeof orderBatches_mutations_bulkUpdateBatchOrders;
  "orderBatches/mutations/createBatch": typeof orderBatches_mutations_createBatch;
  "orderBatches/mutations/deleteBatch": typeof orderBatches_mutations_deleteBatch;
  "orderBatches/mutations/index": typeof orderBatches_mutations_index;
  "orderBatches/mutations/removeOrdersFromBatch": typeof orderBatches_mutations_removeOrdersFromBatch;
  "orderBatches/mutations/updateBatch": typeof orderBatches_mutations_updateBatch;
  "orderBatches/queries/getBatchById": typeof orderBatches_queries_getBatchById;
  "orderBatches/queries/getBatchOrders": typeof orderBatches_queries_getBatchOrders;
  "orderBatches/queries/getBatches": typeof orderBatches_queries_getBatches;
  "orderBatches/queries/index": typeof orderBatches_queries_index;
  "orders/actions/sendOrderConfirmationEmail": typeof orders_actions_sendOrderConfirmationEmail;
  "orders/actions/sendOrderStatusEmail": typeof orders_actions_sendOrderStatusEmail;
  "orders/mutations/cancelOrder": typeof orders_mutations_cancelOrder;
  "orders/mutations/confirmOrderReceived": typeof orders_mutations_confirmOrderReceived;
  "orders/mutations/createOrder": typeof orders_mutations_createOrder;
  "orders/mutations/createOrderLog": typeof orders_mutations_createOrderLog;
  "orders/mutations/createPaymongoCheckoutForOrder": typeof orders_mutations_createPaymongoCheckoutForOrder;
  "orders/mutations/createXenditInvoiceForOrder": typeof orders_mutations_createXenditInvoiceForOrder;
  "orders/mutations/deleteOrder": typeof orders_mutations_deleteOrder;
  "orders/mutations/index": typeof orders_mutations_index;
  "orders/mutations/processCreateOrder": typeof orders_mutations_processCreateOrder;
  "orders/mutations/refreshPaymongoCheckout": typeof orders_mutations_refreshPaymongoCheckout;
  "orders/mutations/refreshXenditInvoice": typeof orders_mutations_refreshXenditInvoice;
  "orders/mutations/restoreOrder": typeof orders_mutations_restoreOrder;
  "orders/mutations/updateOrder": typeof orders_mutations_updateOrder;
  "orders/mutations/updateOrderPaymongoCheckout": typeof orders_mutations_updateOrderPaymongoCheckout;
  "orders/mutations/updateOrderStats": typeof orders_mutations_updateOrderStats;
  "orders/mutations/updateOrderWithNote": typeof orders_mutations_updateOrderWithNote;
  "orders/mutations/updateOrderXenditInvoice": typeof orders_mutations_updateOrderXenditInvoice;
  "orders/mutations/updateOrdersInvoiceForSession": typeof orders_mutations_updateOrdersInvoiceForSession;
  "orders/queries/getDashboardAnalytics": typeof orders_queries_getDashboardAnalytics;
  "orders/queries/getOrderAnalytics": typeof orders_queries_getOrderAnalytics;
  "orders/queries/getOrderById": typeof orders_queries_getOrderById;
  "orders/queries/getOrderLogs": typeof orders_queries_getOrderLogs;
  "orders/queries/getOrders": typeof orders_queries_getOrders;
  "orders/queries/getOrdersByCheckoutSession": typeof orders_queries_getOrdersByCheckoutSession;
  "orders/queries/getOrdersPage": typeof orders_queries_getOrdersPage;
  "orders/queries/index": typeof orders_queries_index;
  "orders/queries/searchOrders": typeof orders_queries_searchOrders;
  "organizations/mutations/addMember": typeof organizations_mutations_addMember;
  "organizations/mutations/createInviteLink": typeof organizations_mutations_createInviteLink;
  "organizations/mutations/createOrganization": typeof organizations_mutations_createOrganization;
  "organizations/mutations/deactivateInviteLink": typeof organizations_mutations_deactivateInviteLink;
  "organizations/mutations/deleteOrganization": typeof organizations_mutations_deleteOrganization;
  "organizations/mutations/index": typeof organizations_mutations_index;
  "organizations/mutations/joinOrganization": typeof organizations_mutations_joinOrganization;
  "organizations/mutations/joinPublicOrganization": typeof organizations_mutations_joinPublicOrganization;
  "organizations/mutations/removeMember": typeof organizations_mutations_removeMember;
  "organizations/mutations/requestToJoinOrganization": typeof organizations_mutations_requestToJoinOrganization;
  "organizations/mutations/reviewJoinRequest": typeof organizations_mutations_reviewJoinRequest;
  "organizations/mutations/updateChatwootConfig": typeof organizations_mutations_updateChatwootConfig;
  "organizations/mutations/updateMemberActivity": typeof organizations_mutations_updateMemberActivity;
  "organizations/mutations/updateMemberRole": typeof organizations_mutations_updateMemberRole;
  "organizations/mutations/updateOrganization": typeof organizations_mutations_updateOrganization;
  "organizations/mutations/updateOrganizationStats": typeof organizations_mutations_updateOrganizationStats;
  "organizations/queries/checkOrganizationPermission": typeof organizations_queries_checkOrganizationPermission;
  "organizations/queries/getChatwootConfig": typeof organizations_queries_getChatwootConfig;
  "organizations/queries/getInviteLinkByCode": typeof organizations_queries_getInviteLinkByCode;
  "organizations/queries/getMyJoinRequestStatus": typeof organizations_queries_getMyJoinRequestStatus;
  "organizations/queries/getOrganizationAnalytics": typeof organizations_queries_getOrganizationAnalytics;
  "organizations/queries/getOrganizationById": typeof organizations_queries_getOrganizationById;
  "organizations/queries/getOrganizationByName": typeof organizations_queries_getOrganizationByName;
  "organizations/queries/getOrganizationBySlug": typeof organizations_queries_getOrganizationBySlug;
  "organizations/queries/getOrganizationInviteLinks": typeof organizations_queries_getOrganizationInviteLinks;
  "organizations/queries/getOrganizationMembers": typeof organizations_queries_getOrganizationMembers;
  "organizations/queries/getOrganizations": typeof organizations_queries_getOrganizations;
  "organizations/queries/getOrganizationsByUser": typeof organizations_queries_getOrganizationsByUser;
  "organizations/queries/getPopularOrganizations": typeof organizations_queries_getPopularOrganizations;
  "organizations/queries/index": typeof organizations_queries_index;
  "organizations/queries/listJoinRequests": typeof organizations_queries_listJoinRequests;
  "organizations/queries/searchOrganizations": typeof organizations_queries_searchOrganizations;
  "payments/actions/createGroupedPaymongoCheckout": typeof payments_actions_createGroupedPaymongoCheckout;
  "payments/actions/createGroupedXenditInvoice": typeof payments_actions_createGroupedXenditInvoice;
  "payments/actions/createXenditInvoice": typeof payments_actions_createXenditInvoice;
  "payments/actions/index": typeof payments_actions_index;
  "payments/actions/paymongoService": typeof payments_actions_paymongoService;
  "payments/actions/sendPaymentConfirmationEmail": typeof payments_actions_sendPaymentConfirmationEmail;
  "payments/actions/xenditService": typeof payments_actions_xenditService;
  "payments/index": typeof payments_index;
  "payments/mutations/createPayment": typeof payments_mutations_createPayment;
  "payments/mutations/deletePayment": typeof payments_mutations_deletePayment;
  "payments/mutations/handleCheckoutSessionExpiry": typeof payments_mutations_handleCheckoutSessionExpiry;
  "payments/mutations/handlePaymongoWebhook": typeof payments_mutations_handlePaymongoWebhook;
  "payments/mutations/handleXenditWebhook": typeof payments_mutations_handleXenditWebhook;
  "payments/mutations/index": typeof payments_mutations_index;
  "payments/mutations/refundPayment": typeof payments_mutations_refundPayment;
  "payments/mutations/restorePayment": typeof payments_mutations_restorePayment;
  "payments/mutations/updatePayment": typeof payments_mutations_updatePayment;
  "payments/mutations/updatePaymentStats": typeof payments_mutations_updatePaymentStats;
  "payments/queries/getPaymentAnalytics": typeof payments_queries_getPaymentAnalytics;
  "payments/queries/getPaymentById": typeof payments_queries_getPaymentById;
  "payments/queries/getPayments": typeof payments_queries_getPayments;
  "payments/queries/index": typeof payments_queries_index;
  "payments/queries/searchPayments": typeof payments_queries_searchPayments;
  "payouts/actions/index": typeof payouts_actions_index;
  "payouts/actions/nodeActions": typeof payouts_actions_nodeActions;
  "payouts/actions/triggerActions": typeof payouts_actions_triggerActions;
  "payouts/index": typeof payouts_index;
  "payouts/mutations/generatePayoutInvoices": typeof payouts_mutations_generatePayoutInvoices;
  "payouts/mutations/index": typeof payouts_mutations_index;
  "payouts/mutations/markInvoicePaid": typeof payouts_mutations_markInvoicePaid;
  "payouts/mutations/revertPayoutStatus": typeof payouts_mutations_revertPayoutStatus;
  "payouts/mutations/updateInvoiceEmailSent": typeof payouts_mutations_updateInvoiceEmailSent;
  "payouts/mutations/updateInvoicePdfUrl": typeof payouts_mutations_updateInvoicePdfUrl;
  "payouts/mutations/updateOrgBankDetails": typeof payouts_mutations_updateOrgBankDetails;
  "payouts/mutations/updateOrgPlatformFee": typeof payouts_mutations_updateOrgPlatformFee;
  "payouts/mutations/updatePayoutSettings": typeof payouts_mutations_updatePayoutSettings;
  "payouts/queries/getAuthorizedPayoutInvoice": typeof payouts_queries_getAuthorizedPayoutInvoice;
  "payouts/queries/getPayoutAdjustments": typeof payouts_queries_getPayoutAdjustments;
  "payouts/queries/getPayoutInvoiceById": typeof payouts_queries_getPayoutInvoiceById;
  "payouts/queries/getPayoutInvoices": typeof payouts_queries_getPayoutInvoices;
  "payouts/queries/getPayoutSettings": typeof payouts_queries_getPayoutSettings;
  "payouts/queries/getPayoutSummary": typeof payouts_queries_getPayoutSummary;
  "payouts/queries/getPendingCount": typeof payouts_queries_getPendingCount;
  "payouts/queries/index": typeof payouts_queries_index;
  "permissions/mutations/assignOrganizationPermission": typeof permissions_mutations_assignOrganizationPermission;
  "permissions/mutations/assignUserPermission": typeof permissions_mutations_assignUserPermission;
  "permissions/mutations/bulkAssignUserPermissions": typeof permissions_mutations_bulkAssignUserPermissions;
  "permissions/mutations/createPermission": typeof permissions_mutations_createPermission;
  "permissions/mutations/deletePermission": typeof permissions_mutations_deletePermission;
  "permissions/mutations/index": typeof permissions_mutations_index;
  "permissions/mutations/revokeOrganizationPermission": typeof permissions_mutations_revokeOrganizationPermission;
  "permissions/mutations/revokeUserPermission": typeof permissions_mutations_revokeUserPermission;
  "permissions/mutations/updatePermission": typeof permissions_mutations_updatePermission;
  "permissions/queries/checkEntityPermission": typeof permissions_queries_checkEntityPermission;
  "permissions/queries/getOrganizationMemberPermissions": typeof permissions_queries_getOrganizationMemberPermissions;
  "permissions/queries/getPermissionAnalytics": typeof permissions_queries_getPermissionAnalytics;
  "permissions/queries/getPermissionByCode": typeof permissions_queries_getPermissionByCode;
  "permissions/queries/getPermissionById": typeof permissions_queries_getPermissionById;
  "permissions/queries/getPermissionUsageSummary": typeof permissions_queries_getPermissionUsageSummary;
  "permissions/queries/getPermissions": typeof permissions_queries_getPermissions;
  "permissions/queries/getPermissionsByCategory": typeof permissions_queries_getPermissionsByCategory;
  "permissions/queries/getUserPermissions": typeof permissions_queries_getUserPermissions;
  "permissions/queries/index": typeof permissions_queries_index;
  "permissions/queries/searchPermissions": typeof permissions_queries_searchPermissions;
  "products/mutations/bulkOperations": typeof products_mutations_bulkOperations;
  "products/mutations/createProduct": typeof products_mutations_createProduct;
  "products/mutations/deleteProduct": typeof products_mutations_deleteProduct;
  "products/mutations/index": typeof products_mutations_index;
  "products/mutations/manageProductImages": typeof products_mutations_manageProductImages;
  "products/mutations/manageVariants": typeof products_mutations_manageVariants;
  "products/mutations/restoreProduct": typeof products_mutations_restoreProduct;
  "products/mutations/updateProduct": typeof products_mutations_updateProduct;
  "products/mutations/updateProductStats": typeof products_mutations_updateProductStats;
  "products/queries/getAllActiveProducts": typeof products_queries_getAllActiveProducts;
  "products/queries/getPopularProducts": typeof products_queries_getPopularProducts;
  "products/queries/getProductAnalytics": typeof products_queries_getProductAnalytics;
  "products/queries/getProductByCode": typeof products_queries_getProductByCode;
  "products/queries/getProductById": typeof products_queries_getProductById;
  "products/queries/getProductBySlug": typeof products_queries_getProductBySlug;
  "products/queries/getProductRecommendations": typeof products_queries_getProductRecommendations;
  "products/queries/getProducts": typeof products_queries_getProducts;
  "products/queries/index": typeof products_queries_index;
  "products/queries/searchProducts": typeof products_queries_searchProducts;
  "refundRequests/actions/index": typeof refundRequests_actions_index;
  "refundRequests/actions/sendRefundRequestEmail": typeof refundRequests_actions_sendRefundRequestEmail;
  "refundRequests/index": typeof refundRequests_index;
  "refundRequests/mutations/approveRefundRequest": typeof refundRequests_mutations_approveRefundRequest;
  "refundRequests/mutations/createRefundNotification": typeof refundRequests_mutations_createRefundNotification;
  "refundRequests/mutations/createRefundRequest": typeof refundRequests_mutations_createRefundRequest;
  "refundRequests/mutations/createRefundVoucher": typeof refundRequests_mutations_createRefundVoucher;
  "refundRequests/mutations/index": typeof refundRequests_mutations_index;
  "refundRequests/mutations/rejectRefundRequest": typeof refundRequests_mutations_rejectRefundRequest;
  "refundRequests/queries/getPendingCount": typeof refundRequests_queries_getPendingCount;
  "refundRequests/queries/getRefundRequestById": typeof refundRequests_queries_getRefundRequestById;
  "refundRequests/queries/getRefundRequestByOrder": typeof refundRequests_queries_getRefundRequestByOrder;
  "refundRequests/queries/getRefundRequests": typeof refundRequests_queries_getRefundRequests;
  "refundRequests/queries/getRefundRequestsByUser": typeof refundRequests_queries_getRefundRequestsByUser;
  "refundRequests/queries/index": typeof refundRequests_queries_index;
  "reviews/index": typeof reviews_index;
  "reviews/mutations/createReview": typeof reviews_mutations_createReview;
  "reviews/mutations/index": typeof reviews_mutations_index;
  "reviews/mutations/updateReview": typeof reviews_mutations_updateReview;
  "reviews/queries/getReviewsByProduct": typeof reviews_queries_getReviewsByProduct;
  "reviews/queries/getUserReview": typeof reviews_queries_getUserReview;
  "reviews/queries/index": typeof reviews_queries_index;
  "seeds/index": typeof seeds_index;
  "seeds/seedData": typeof seeds_seedData;
  "seeds/seedPayoutAdjustments": typeof seeds_seedPayoutAdjustments;
  "storefrontApplications/mutations/index": typeof storefrontApplications_mutations_index;
  "storefrontApplications/mutations/submit": typeof storefrontApplications_mutations_submit;
  "storefrontApplications/mutations/updateApplicationStatus": typeof storefrontApplications_mutations_updateApplicationStatus;
  "storefrontApplications/mutations/updateStatus": typeof storefrontApplications_mutations_updateStatus;
  "storefrontApplications/queries/index": typeof storefrontApplications_queries_index;
  "storefrontApplications/queries/list": typeof storefrontApplications_queries_list;
  "storefrontApplications/queries/listApplications": typeof storefrontApplications_queries_listApplications;
  "surveys/index": typeof surveys_index;
  "surveys/mutations/index": typeof surveys_mutations_index;
  "surveys/mutations/manageSurveyCategory": typeof surveys_mutations_manageSurveyCategory;
  "surveys/mutations/markSurveyResponseFollowUp": typeof surveys_mutations_markSurveyResponseFollowUp;
  "surveys/mutations/submitSurveyResponse": typeof surveys_mutations_submitSurveyResponse;
  "surveys/mutations/updateSurveyCategoryStats": typeof surveys_mutations_updateSurveyCategoryStats;
  "surveys/queries/index": typeof surveys_queries_index;
  "surveys/queries/surveyAnalytics": typeof surveys_queries_surveyAnalytics;
  "surveys/queries/surveyCategories": typeof surveys_queries_surveyCategories;
  "surveys/queries/surveyResponses": typeof surveys_queries_surveyResponses;
  testHelpers: typeof testHelpers;
  "tickets/constants": typeof tickets_constants;
  "tickets/index": typeof tickets_index;
  "tickets/mutations/createTicket": typeof tickets_mutations_createTicket;
  "tickets/mutations/deleteTicket": typeof tickets_mutations_deleteTicket;
  "tickets/mutations/index": typeof tickets_mutations_index;
  "tickets/mutations/manageAssignee": typeof tickets_mutations_manageAssignee;
  "tickets/mutations/manageReads": typeof tickets_mutations_manageReads;
  "tickets/mutations/manageTicketUpdates": typeof tickets_mutations_manageTicketUpdates;
  "tickets/mutations/restoreTicket": typeof tickets_mutations_restoreTicket;
  "tickets/mutations/updateTicket": typeof tickets_mutations_updateTicket;
  "tickets/mutations/updateTicketStats": typeof tickets_mutations_updateTicketStats;
  "tickets/queries/getOpenCount": typeof tickets_queries_getOpenCount;
  "tickets/queries/getTicketAnalytics": typeof tickets_queries_getTicketAnalytics;
  "tickets/queries/getTicketById": typeof tickets_queries_getTicketById;
  "tickets/queries/getTicketUpdates": typeof tickets_queries_getTicketUpdates;
  "tickets/queries/getTickets": typeof tickets_queries_getTickets;
  "tickets/queries/getTicketsPage": typeof tickets_queries_getTicketsPage;
  "tickets/queries/getUnreadCount": typeof tickets_queries_getUnreadCount;
  "tickets/queries/index": typeof tickets_queries_index;
  "tickets/queries/searchTickets": typeof tickets_queries_searchTickets;
  "users/actions/generateChatwootHmac": typeof users_actions_generateChatwootHmac;
  "users/actions/index": typeof users_actions_index;
  "users/actions/sendWelcomeEmail": typeof users_actions_sendWelcomeEmail;
  "users/mutations/addOrganizationMembership": typeof users_mutations_addOrganizationMembership;
  "users/mutations/clerkWebhook": typeof users_mutations_clerkWebhook;
  "users/mutations/completeOnboarding": typeof users_mutations_completeOnboarding;
  "users/mutations/createChatwootHmacToken": typeof users_mutations_createChatwootHmacToken;
  "users/mutations/deleteUser": typeof users_mutations_deleteUser;
  "users/mutations/index": typeof users_mutations_index;
  "users/mutations/removeOrganizationMembership": typeof users_mutations_removeOrganizationMembership;
  "users/mutations/restoreUser": typeof users_mutations_restoreUser;
  "users/mutations/updateAccountSettings": typeof users_mutations_updateAccountSettings;
  "users/mutations/updateLastLogin": typeof users_mutations_updateLastLogin;
  "users/mutations/updateOrderStats": typeof users_mutations_updateOrderStats;
  "users/mutations/updatePreferences": typeof users_mutations_updatePreferences;
  "users/mutations/updateProfile": typeof users_mutations_updateProfile;
  "users/mutations/updateUserPermissions": typeof users_mutations_updateUserPermissions;
  "users/mutations/updateUserRole": typeof users_mutations_updateUserRole;
  "users/queries/checkUserPermission": typeof users_queries_checkUserPermission;
  "users/queries/getAccountSettings": typeof users_queries_getAccountSettings;
  "users/queries/getChatwootHmacToken": typeof users_queries_getChatwootHmacToken;
  "users/queries/getCurrentUser": typeof users_queries_getCurrentUser;
  "users/queries/getRecentlyActiveUsers": typeof users_queries_getRecentlyActiveUsers;
  "users/queries/getUserAnalytics": typeof users_queries_getUserAnalytics;
  "users/queries/getUserByEmail": typeof users_queries_getUserByEmail;
  "users/queries/getUserById": typeof users_queries_getUserById;
  "users/queries/getUsers": typeof users_queries_getUsers;
  "users/queries/getUsersByManager": typeof users_queries_getUsersByManager;
  "users/queries/getUsersByOrganization": typeof users_queries_getUsersByOrganization;
  "users/queries/index": typeof users_queries_index;
  "users/queries/searchUsers": typeof users_queries_searchUsers;
  "voucherRefundRequests/index": typeof voucherRefundRequests_index;
  "voucherRefundRequests/mutations/approveVoucherRefundRequest": typeof voucherRefundRequests_mutations_approveVoucherRefundRequest;
  "voucherRefundRequests/mutations/createVoucherRefundRequest": typeof voucherRefundRequests_mutations_createVoucherRefundRequest;
  "voucherRefundRequests/mutations/index": typeof voucherRefundRequests_mutations_index;
  "voucherRefundRequests/mutations/rejectVoucherRefundRequest": typeof voucherRefundRequests_mutations_rejectVoucherRefundRequest;
  "voucherRefundRequests/queries/getVoucherRefundRequestById": typeof voucherRefundRequests_queries_getVoucherRefundRequestById;
  "voucherRefundRequests/queries/getVoucherRefundRequestCounts": typeof voucherRefundRequests_queries_getVoucherRefundRequestCounts;
  "voucherRefundRequests/queries/getVoucherRefundRequests": typeof voucherRefundRequests_queries_getVoucherRefundRequests;
  "voucherRefundRequests/queries/getVoucherRefundRequestsByUser": typeof voucherRefundRequests_queries_getVoucherRefundRequestsByUser;
  "voucherRefundRequests/queries/getVoucherRefundRequestsByVoucher": typeof voucherRefundRequests_queries_getVoucherRefundRequestsByVoucher;
  "voucherRefundRequests/queries/index": typeof voucherRefundRequests_queries_index;
  "vouchers/index": typeof vouchers_index;
  "vouchers/mutations/createVoucher": typeof vouchers_mutations_createVoucher;
  "vouchers/mutations/deleteVoucher": typeof vouchers_mutations_deleteVoucher;
  "vouchers/mutations/index": typeof vouchers_mutations_index;
  "vouchers/mutations/toggleVoucherStatus": typeof vouchers_mutations_toggleVoucherStatus;
  "vouchers/mutations/updateVoucher": typeof vouchers_mutations_updateVoucher;
  "vouchers/queries/getVoucherByCode": typeof vouchers_queries_getVoucherByCode;
  "vouchers/queries/getVoucherById": typeof vouchers_queries_getVoucherById;
  "vouchers/queries/getVouchers": typeof vouchers_queries_getVouchers;
  "vouchers/queries/getVouchersByUser": typeof vouchers_queries_getVouchersByUser;
  "vouchers/queries/index": typeof vouchers_queries_index;
  "vouchers/queries/validateVoucher": typeof vouchers_queries_validateVoucher;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  r2: {
    lib: {
      deleteMetadata: FunctionReference<
        "mutation",
        "internal",
        { bucket: string; key: string },
        null
      >;
      deleteObject: FunctionReference<
        "mutation",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          endpoint: string;
          key: string;
          secretAccessKey: string;
        },
        null
      >;
      deleteR2Object: FunctionReference<
        "action",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          endpoint: string;
          key: string;
          secretAccessKey: string;
        },
        null
      >;
      getMetadata: FunctionReference<
        "query",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          endpoint: string;
          key: string;
          secretAccessKey: string;
        },
        {
          bucket: string;
          bucketLink: string;
          contentType?: string;
          key: string;
          lastModified: string;
          link: string;
          sha256?: string;
          size?: number;
          url: string;
        } | null
      >;
      listMetadata: FunctionReference<
        "query",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          cursor?: string;
          endpoint: string;
          limit?: number;
          secretAccessKey: string;
        },
        {
          continueCursor: string;
          isDone: boolean;
          page: Array<{
            bucket: string;
            bucketLink: string;
            contentType?: string;
            key: string;
            lastModified: string;
            link: string;
            sha256?: string;
            size?: number;
            url: string;
          }>;
          pageStatus?: null | "SplitRecommended" | "SplitRequired";
          splitCursor?: null | string;
        }
      >;
      store: FunctionReference<
        "action",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          endpoint: string;
          secretAccessKey: string;
          url: string;
        },
        any
      >;
      syncMetadata: FunctionReference<
        "action",
        "internal",
        {
          accessKeyId: string;
          bucket: string;
          endpoint: string;
          key: string;
          onComplete?: string;
          secretAccessKey: string;
        },
        null
      >;
      upsertMetadata: FunctionReference<
        "mutation",
        "internal",
        {
          bucket: string;
          contentType?: string;
          key: string;
          lastModified: string;
          link: string;
          sha256?: string;
          size?: number;
        },
        { isNew: boolean }
      >;
    };
  };
};
